using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RacksStand.Enum.Core
{
    public enum Language : int
    {
        CHINESEMANDARIN = 1,
        SPANISH = 2,
        ENGLISH = 3,
        BENGALI = 4,
        HINDI = 5,
        PORTUGUESE = 6,
        RUSSIAN = 7,
        JAPANESE = 8,
        GERMANSTANDARD = 9,
        CHINESEWU = 10,
        JAVANESE = 11,
        KOREAN = 12,
        FRENCH = 13,
        VIETNAMESE = 14,
        TELUGU = 15,
        CHINESEYUE = 16,
        MARATHI = 17,
        TAMIL = 18,
        TURKISH = 19,
        URDU = 20,
        CHINESEMINNAN = 21,
        CHINESEJINYU = 22,
        GUJARATI = 23,
        POLISH = 24,
        ARABICEGYPTIANSPOKEN = 25,
        UKRAINIAN = 26,
        ITALIAN = 27,
        CHINESEXIANG = 28,
        MALAYALAM = 29,
        CHINESEHAKKA = 30,
        KANNADA = 31,
        ORIYA = 32,
        PANJABIWESTERN = 33,
        SUNDA = 34,
        PANJABIEASTERN = 35,
        ROMANIAN = 36,
        BHOJPURI = 37,
        AZERBAIJANISOUTH = 38,
        FARSIWESTERN = 39,
        MAITHILI = 40,
        HAUSA = 41,
        ARABICALGERIANSPOKEN = 42,
        BURMESE = 43,
        SERBOCROATIAN = 44,
        CHINESEGAN = 45,
        AWADHI = 46,
        THAI = 47,
        DUTCH = 48,
        YORUBA = 49,
        SINDHI = 50,
        ARABICMOROCCANSPOKEN = 51,
        ARABICSAIDISPOKEN = 52,
        UZBEKNORTHERN = 53,
        MALAY = 54,
        AMHARIC = 55,
        INDONESIAN = 56,
        IGBO = 57,
        TAGALOG = 58,
        NEPALI = 59,
        ARABICSUDANESESPOKEN = 60,
        SARAIKI = 61,
        CEBUANO = 62,
        ARABICNORTHLEVANTINESPOKEN = 63,
        THAINORTHEASTERN = 64,
        ASSAMESE = 65,
        HUNGARIAN = 66,
        CHITTAGONIAN = 67,
        ARABICMESOPOTAMIANSPOKEN = 68,
        MADURA = 69,
        SINHALA = 70,
        HARYANVI = 71,
        MARWARI = 72,
        CZECH = 73,
        GREEK = 74,
        MAGAHI = 75,
        CHHATTISGARHI = 76,
        DECCAN = 77,
        CHINESEMINBEI = 78,
        BELARUSAN = 79,
        ZHUANGNORTHERN = 80,
        ARABICNAJDISPOKEN = 81,
        PASHTONORTHERN = 82,
        SOMALI = 83,
        MALAGASY = 84,
        ARABICTUNISIANSPOKEN = 85,
        RWANDA = 86,
        ZULU = 87,
        BULGARIAN = 88,
        SWEDISH = 89,
        LOMBARD = 90,
        OROMOWESTCENTRAL = 91,
        PASHTOSOUTHERN = 92,
        KAZAKH = 93,
        ILOCANO = 94,
        TATAR = 95,
        FULFULDENIGERIAN = 96,
        ARABICSANAANISPOKEN = 97,
        UYGHUR = 98,
        HAITIANCREOLEFRENCH = 99,
        AZERBAIJANINORTH = 100,
        NAPOLETANOCALABRESE = 101,
        KHMERCENTRAL = 102,
        FARSIEASTERN = 103,
        AKAN = 104,
        HILIGAYNON = 105,
        KURMANJI = 106,
        SHONA = 107,
    }
}
