export namespace Helper {

    export class GUID {
        public static Empty() { return "00000000-0000-0000-0000-000000000000" }
        public static NewID() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }
    }
    export class AppConfig {
        public static COOKIE_USERNAME_KEY: string = 'UserName';
        public static COOKIE_PASSWORD_KEY: string = 'Password';
        public static SESSION_KEY: string = 'SessionId';
        public static BASE_URL: string = 'http://localhost/WebAPI/api/'; 
    }
    export class Collection {

        public static getSalutation():string[]
        {
           let listSalutation:string[]=['Mr.','Mrs.','Ms.','Miss','Dr.'];
           return listSalutation;
        }

        public static getCountryies(): Country[] {
            let listCountry: Country[] = [
                { name: 'Afghanistan', id: 1 },
                { name: 'AlandIslands ', id: 2 },
                { name: ' Albania ', id: 3 },
                { name: ' Algeria ', id: 4 },
                { name: ' American Samoa ', id: 5 },
                { name: ' Andorra ', id: 6 },
                { name: ' Angola ', id: 7 },
                { name: ' Anguilla ', id: 8 },
                { name: ' Antarctica ', id: 9 },
                { name: ' Antigua and Barbuda ', id: 10 },
                { name: ' Argentina ', id: 11 },
                { name: ' Armenia ', id: 12 },
                { name: ' Aruba ', id: 13 },
                { name: ' Australia ', id: 14 },
                { name: ' Austria ', id: 15 },
                { name: ' Azerbaijan ', id: 16 },
                { name: ' Bahamas ', id: 17 },
                { name: ' Bahrain ', id: 18 },
                { name: ' Bangladesh ', id: 19 },
                { name: ' Barbados ', id: 20 },
                { name: ' Belarus ', id: 21 },
                { name: ' Belgium ', id: 22 },
                { name: ' Belize ', id: 23 },
                { name: ' Benin ', id: 24 },
                { name: ' Bermuda ', id: 25 },
                { name: ' Bhutan ', id: 26 },
                { name: ' Bolivia Plurinational State of', id: 27 },  //issue.
                { name: ' Bonaire Sint Eustatius and Saba', id: 28 },
                { name: ' Bosnia and Herzegovina', id: 29 },
                { name: 'Botswana ', id: 30 },
                { name: ' Bouvet Island ', id: 31 },
                { name: ' Brazil ', id: 32 },
                { name: ' British Indian Ocean Territory ', id: 33 },
                { name: ' Brunei Darussalam ', id: 34 },
                { name: ' Bulgaria ', id: 35 },
                { name: ' Burkina Faso ', id: 36 },
                { name: ' Burundi ', id: 37 },
                { name: ' Cambodia ', id: 38 },
                { name: ' Cameroon ', id: 39 },
                { name: 'Canada ', id: 40 },
                { name: '  Cape Verde ', id: 41 },
                { name: ' Cayman Islands ', id: 42 },
                { name: ' Central African Republic ', id: 43 },
                { name: 'Chad ', id: 44 },
                { name: '  Chile ', id: 45 },
                { name: '  China ', id: 46 },
                { name: '  Christmas Island ', id: 47 },
                { name: '  Cocos Keeling Islands ', id: 48 },
                { name: '  Colombia ', id: 49 },
                { name: '  Comoros ', id: 50 },
                { name: '  Congo ', id: 51 },
                { name: '  Congo The Democratic Republic Of The', id: 52 }, //issue
                { name: ' Cook Islands ', id: 53 },
                { name: ' Costa Rica ', id: 54 },
                { name: 'C�ted Ivoire ', id: 55 },
                { name: ' Croatia ', id: 56 },
                { name: '  Cuba ', id: 57 },
                { name: '  Cura�ao ', id: 58 },
                { name: '  Cyprus ', id: 59 },
                { name: '  Czech Republic ', id: 60 },
                { name: '  Denmark ', id: 61 },
                { name: '  Djibouti ', id: 62 },
                { name: '  Dominica ', id: 63 },
                { name: '  Dominican Republic ', id: 64 },
                { name: ' Ecuador ', id: 65 },
                { name: ' Egypt ', id: 66 },
                { name: ' ElSalvador ', id: 67 },
                { name: ' Equatorial Guinea ', id: 68 },
                { name: ' Eritrea ', id: 69 },
                { name: ' Estonia ', id: 70 },
                { name: ' Ethiopia ', id: 71 },
                { name: ' Falkland Islands Malvinas ', id: 72 },
                { name: ' Faroe Islands ', id: 73 },
                { name: ' Fiji ', id: 74 },
                { name: ' Finland ', id: 75 },
                { name: ' France ', id: 76 },
                { name: ' French Guiana ', id: 77 },
                { name: ' French Polynesia ', id: 78 },
                { name: ' French Southern Territories ', id: 79 },
                { name: ' Gabon ', id: 80 },
                { name: ' Gambia ', id: 81 },
                { name: ' Georgia ', id: 82 },
                { name: ' Germany ', id: 83 },
                { name: 'Ghana ', id: 84 },
                { name: ' Gibraltar ', id: 85 },
                { name: ' Greece ', id: 86 },
                { name: ' Greenland ', id: 87 },
                { name: ' Grenada ', id: 88 },
                { name: ' Guadeloupe ', id: 89 },
                { name: ' Guam ', id: 90 },
                { name: 'Guatemala ', id: 91 },
                { name: ' Guernsey ', id: 92 },
                { name: '  Guinea ', id: 93 },
                { name: '  Guinea Bissau ', id: 94 },
                { name: '  Guyana ', id: 95 },
                { name: ' Haiti ', id: 96 },
                { name: ' Heard Island and McDonald Islands ', id: 97 },
                { name: 'HolySeeVaticanCity State ', id: 98 }, //nop
                { name: ' Honduras ', id: 99 },
                { name: ' HongKong ', id: 100 },
                { name: ' Hungary ', id: 101 },
                { name: ' Iceland ', id: 102 },
                { name: ' India ', id: 103 },
                { name: ' Indonesia ', id: 104 },
                { name: ' Iran Islamic Republic Of ', id: 105 }, //issue
                { name: ' Iraq ', id: 106 },
                { name: ' Ireland ', id: 107 },
                { name: ' Isle Of Man ', id: 108 },
                { name: 'Israel ', id: 109 },
                { name: ' Italy ', id: 110 },
                { name: ' Jamaica ', id: 111 },
                { name: ' Japan ', id: 112 },
                { name: 'Jersey ', id: 113 },
                { name: ' Jordan ', id: 114 },
                { name: ' Kazakhstan ', id: 115 },
                { name: ' Kenya ', id: 116 },
                { name: ' Kiribati ', id: 117 },
                { name: ' Korea Democratic Peoples Republic Of ', id: 118 }, //issue
                { name: ' Korea Republic Of ', id: 119 }, //issue
                { name: 'Kuwait ', id: 120 },
                { name: 'Kyrgyzstan ', id: 121 },
                { name: 'Lao Peoples Democratic Republic ', id: 122 },
                { name: 'Latvia ', id: 123 },
                { name: 'Lebanon ', id: 124 },
                { name: 'Lesotho ', id: 125 },
                { name: 'Liberia ', id: 126 },
                { name: 'Libya ', id: 127 },
                { name: 'Liechtenstein ', id: 128 },
                { name: 'Lithuania ', id: 129 },
                { name: 'Luxembourg ', id: 130 },
                { name: 'Macao ', id: 131 },
                { name: 'MacedoniaTthe Former Yugoslav RepublicOf ', id: 132 }, //issue
                { name: 'Madagascar ', id: 133 },
                { name: 'Malawi ', id: 134 },
                { name: 'Malaysia ', id: 135 },
                { name: 'Maldives ', id: 136 },
                { name: 'Mali ', id: 137 },
                { name: 'Malta ', id: 138 },
                { name: 'Marshall Islands ', id: 139 },
                { name: 'Martinique ', id: 140 },
                { name: 'Mauritania ', id: 141 },
                { name: 'Mauritius ', id: 142 },
                { name: 'Mayotte ', id: 143 },
                { name: 'Mexico ', id: 144 },
                { name: 'Micronesia Federated StatesOf ', id: 145 }, //issue
                { name: 'Moldova RepublicOf ', id: 146 }, //issue
                { name: 'Monaco ', id: 147 },
                { name: 'Mongolia ', id: 148 },
                { name: 'Montenegro ', id: 149 },
                { name: 'Montserrat ', id: 150 },
                { name: 'Morocco ', id: 151 },
                { name: 'Mozambique ', id: 152 },
                { name: 'Myanmar ', id: 153 },
                { name: 'Namibia ', id: 154 },
                { name: 'Nauru ', id: 155 },
                { name: 'Nepal ', id: 156 },
                { name: 'Netherlands ', id: 157 },
                { name: 'NewCaledonia ', id: 158 },
                { name: 'NewZealand ', id: 159 },
                { name: 'Nicaragua ', id: 160 },
                { name: 'Niger ', id: 161 },
                { name: 'Nigeria ', id: 162 },
                { name: 'Niue ', id: 163 },
                { name: 'Norfolk Island ', id: 164 },
                { name: 'Northern Mariana Islands ', id: 165 },
                { name: 'Norway ', id: 166 },
                { name: 'Oman ', id: 167 },
                { name: 'Pakistan ', id: 168 },
                { name: 'Palau ', id: 169 },
                { name: 'Palestinian Territory Occupied ', id: 170 },
                { name: 'Panama ', id: 171 },
                { name: 'Papua New Guinea ', id: 172 },
                { name: 'Paraguay ', id: 173 },
                { name: 'Peru ', id: 174 },
                { name: 'Philippines ', id: 175 },
                { name: 'Pitcairn ', id: 176 },
                { name: 'Poland ', id: 177 },
                { name: 'Portugal ', id: 178 },
                { name: 'PuertoRico ', id: 179 },
                { name: 'Qatar ', id: 180 },
                { name: 'R�union ', id: 181 },
                { name: 'Romania ', id: 182 },
                { name: 'Russian Federation ', id: 183 },
                { name: 'Rwanda ', id: 184 },
                { name: 'SaintBarth�lemy ', id: 185 },
                { name: 'Saint Helena Ascension and Tristanda Cunha ', id: 186 },
                { name: 'Saint Kitts and Nevis ', id: 187 },
                { name: 'Saint Lucia ', id: 188 },
                { name: 'Saint Martin French Part ', id: 189 },
                { name: 'Saint Pierre and Miquelon ', id: 190 },
                { name: 'Saint Vincent and The Grenadines ', id: 191 },
                { name: 'Samoa ', id: 192 },
                { name: 'San Marino ', id: 193 },
                { name: 'Sao Tome and Principe ', id: 194 },
                { name: 'Saudi Arabia ', id: 195 },
                { name: 'Senegal ', id: 196 },
                { name: 'Serbia ', id: 197 },
                { name: 'Seychelles ', id: 198 },
                { name: 'SierraLeone ', id: 199 },
                { name: 'Singapore ', id: 200 },
                { name: 'Sint Maarten Dutch Part ', id: 201 },
                { name: 'Slovakia ', id: 202 },
                { name: 'Slovenia ', id: 203 },
                { name: 'Solomon Islands ', id: 204 },
                { name: 'Somalia ', id: 205 },
                { name: 'SouthAfrica ', id: 206 },
                { name: 'South Georgia and The South Sandwich Islands ', id: 207 },
                { name: 'South Sudan ', id: 208 },
                { name: 'Spain ', id: 209 },
                { name: 'SriLanka ', id: 210 },
                { name: 'Sudan ', id: 211 },
                { name: 'Suriname ', id: 212 },
                { name: 'Svalbard and JanMayen ', id: 213 },
                { name: 'Swaziland ', id: 214 },
                { name: 'Sweden ', id: 215 },
                { name: 'Switzerland ', id: 216 },
                { name: 'Syrian Arab Republic ', id: 217 },
                { name: 'Taiwan Province Of China ', id: 218 },
                { name: 'Tajikistan ', id: 219 },
                { name: 'Tanzania United RepublicOf ', id: 220 },//issue
                { name: 'Thailand ', id: 221 },
                { name: 'Timor Leste ', id: 222 },
                { name: 'Togo ', id: 223 },
                { name: 'Tokelau ', id: 224 },
                { name: 'Tonga ', id: 225 },
                { name: 'Trinidad and Tobago ', id: 226 },
                { name: 'Tunisia ', id: 227 },
                { name: 'Turkey ', id: 228 },
                { name: 'Turkmenistan ', id: 229 },
                { name: 'Turks and Caicos Islands ', id: 230 },
                { name: 'Tuvalu ', id: 231 },
                { name: 'Uganda ', id: 232 },
                { name: 'Ukraine ', id: 233 },
                { name: 'United Arab Emirates ', id: 234 },
                { name: 'United Kingdom ', id: 235 },
                { name: 'United States ', id: 236 },
                { name: 'United States Minor Outlying Islands ', id: 237 },
                { name: 'Uruguay ', id: 238 },
                { name: 'Uzbekistan ', id: 239 },
                { name: 'Vanuatu ', id: 240 },
                { name: 'Venezuela Bolivarian RepublicOf ', id: 241 }, //issue
                { name: 'VietNam ', id: 242 },
                { name: 'Virgin Islands British ', id: 243 },
                { name: 'Virgin IslandsUS ', id: 244 },
                { name: 'Wallis and Futuna ', id: 245 },
                { name: 'Western Sahara', id: 246 },
                { name: 'Yemen ', id: 247 },
                { name: 'Zambia ', id: 248 },
                { name: 'Zimbabwe ', id: 249 }
            ];
            return listCountry;
        }
    }

    

}
export interface Country {
        id: number,
        name: string
    }

